package backend

import (
	"bytes"
	"crypto/tls"
	"encoding/pem"
	"fmt"
	"io"
	"log"
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"crypto/x509/pkix"
	"math/big"
	"net"
	"net/http"
	"net/url"
	"path"
	"strings"
	"sync"
	"time"

	"meowl/backend/traffic" // Generated by script.py

	"regexp"

	"github.com/Knetic/govaluate"
	"github.com/elazarl/goproxy"
	"golang.org/x/net/http2"
	"google.golang.org/protobuf/proto"
	"github.com/quic-go/quic-go/http3"
)

var (
	proxy                 *goproxy.ProxyHttpServer
	interceptEnabled      bool
	requestBreakpoint     bool
	responseBreakpoint    bool
	interceptMu           sync.RWMutex
	pendingRequests       = make(map[string]chan InterceptSignal)
	pendingMu             sync.Mutex
	currentSrv            *http.Server
	currentHub            *Hub
	currentPort           int
	currentAddr           string
	caCert                []byte
	caKey                 []byte
	dnsCache              sync.Map
	interceptResponseNext = make(map[string]bool)
	interceptNextMu       sync.Mutex
)

type dnsEntry struct {
	ips    []string
	expiry time.Time
}

// InterceptSignal carries the action (forward/drop) and optionally the edited raw request
type InterceptSignal struct {
	Action  string
	Payload string
}

func init() {
	proxy = goproxy.NewProxyHttpServer()
	proxy.Verbose = false
	// Initialize with default CA
	caCert = goproxy.GoproxyCa.Certificate[0]
	caKey = nil // Not directly accessible from goproxy.GoproxyCa easily if it's default
}

// --- Rules Application ---

func matchPattern(text, pattern string) bool {
	if pattern == "" {
		return false
	}
	if pattern == ".*" {
		return true
	}
	// Auto-detect regex if /pattern/
	isForcedRegex := strings.HasPrefix(pattern, "/") && strings.HasSuffix(pattern, "/")
	cleanPattern := pattern
	if isForcedRegex {
		cleanPattern = pattern[1 : len(pattern)-1]
	}

	re, err := regexp.Compile(cleanPattern)
	if err == nil {
		return re.MatchString(text)
	}
	// Fallback to contains if not forced regex
	if !isForcedRegex {
		return strings.Contains(strings.ToLower(text), strings.ToLower(pattern))
	}
	return false
}

func replacePattern(text, pattern, replacement string) string {
	isForcedRegex := strings.HasPrefix(pattern, "/") && strings.HasSuffix(pattern, "/")
	cleanPattern := pattern
	if isForcedRegex {
		cleanPattern = pattern[1 : len(pattern)-1]
	}

	re, err := regexp.Compile(cleanPattern)
	if err == nil {
		return re.ReplaceAllString(text, replacement)
	}
	if !isForcedRegex {
		return strings.ReplaceAll(text, pattern, replacement)
	}
	return text
}

func evaluateDSL(expression string, vars map[string]interface{}) bool {
	if expression == "" {
		return true
	}
	expr, err := govaluate.NewEvaluableExpression(expression)
	if err != nil {
		log.Printf("[DSL] Error parsing expression '%s': %v", expression, err)
		return false
	}
	result, err := expr.Evaluate(vars)
	if err != nil {
		log.Printf("[DSL] Error evaluating expression: %v", err)
		return false
	}
	if b, ok := result.(bool); ok {
		return b
	}
	return false
}

func applyRequestRules(r *http.Request, body []byte, category string) ([]byte, bool) {
	rules := GetRules()
	modified := false

	vars := map[string]interface{}{
		"method": r.Method,
		"url":    r.URL.String(),
		"host":   r.Host,
		"path":   r.URL.Path,
		"body":   string(body),
	}

	for _, rule := range rules {
		if !rule.Enabled || !strings.EqualFold(rule.Category, category) {
			continue
		}

		if rule.CelExpression != "" {
			if !evaluateDSL(rule.CelExpression, vars) {
				continue
			}
		}

		ruleType := strings.ToLower(rule.Type)
		ruleScope := strings.ToLower(rule.Scope)

		if ruleType == "drop" || ruleType == "filter" {
			matched := false
			switch ruleScope {
			case "url": matched = matchPattern(r.URL.String(), rule.Pattern)
			case "request_header":
				for _, values := range r.Header {
					for _, v := range values {
						if matchPattern(v, rule.Pattern) { matched = true; break }
					}
					if matched { break }
				}
			case "request_body": matched = matchPattern(string(body), rule.Pattern)
			case "all": matched = matchPattern(r.URL.String(), rule.Pattern) || matchPattern(string(body), rule.Pattern)
			}
			if matched {
				log.Printf("[Rules] Drop triggered for %s", r.URL.String())
				return body, true
			}
		}

		if ruleType == "delay" && rule.DelayMs > 0 {
			matched := false
			switch ruleScope {
			case "url": matched = matchPattern(r.URL.String(), rule.Pattern)
			case "request_body": matched = matchPattern(string(body), rule.Pattern)
			case "all": matched = matchPattern(r.URL.String(), rule.Pattern) || matchPattern(string(body), rule.Pattern)
			}
			if matched {
				time.Sleep(time.Duration(rule.DelayMs) * time.Millisecond)
			}
		}

		if ruleType == "replace" || ruleType == "matchreplace" {
			switch ruleScope {
			case "url":
				u := r.URL.String()
				if matchPattern(u, rule.Pattern) {
					newU := replacePattern(u, rule.Pattern, rule.Replacement)
					if parsed, err := url.Parse(newU); err == nil {
						r.URL = parsed; modified = true
					}
				}
			case "request_header":
				for k, values := range r.Header {
					for i, v := range values {
						if matchPattern(v, rule.Pattern) {
							r.Header[k][i] = replacePattern(v, rule.Pattern, rule.Replacement)
							modified = true
						}
					}
				}
			case "request_body":
				bodyStr := string(body)
				if matchPattern(bodyStr, rule.Pattern) {
					body = []byte(replacePattern(bodyStr, rule.Pattern, rule.Replacement))
					modified = true
				}
			case "all":
				if matchPattern(r.URL.String(), rule.Pattern) {
					newU := replacePattern(r.URL.String(), rule.Pattern, rule.Replacement)
					if parsed, err := url.Parse(newU); err == nil { r.URL = parsed; modified = true }
				}
				for k, values := range r.Header {
					for i, v := range values {
						if matchPattern(v, rule.Pattern) { r.Header[k][i] = replacePattern(v, rule.Pattern, rule.Replacement); modified = true }
					}
				}
				if matchPattern(string(body), rule.Pattern) {
					body = []byte(replacePattern(string(body), rule.Pattern, rule.Replacement))
					modified = true
				}
			}
		}
	}

	return body, modified
}

func applyResponseRules(resp *http.Response, body []byte, category string) ([]byte, bool) {
	rules := GetRules()
	modified := false

	reqURL := ""
	reqHost := ""
	if resp.Request != nil {
		reqURL = resp.Request.URL.String()
		reqHost = resp.Request.Host
	}

	vars := map[string]interface{}{
		"status": resp.StatusCode,
		"url":    reqURL,
		"host":   reqHost,
		"body":   string(body),
		"mime":   resp.Header.Get("Content-Type"),
	}

	for _, rule := range rules {
		if !rule.Enabled || !strings.EqualFold(rule.Category, category) {
			continue
		}

		if rule.CelExpression != "" {
			if !evaluateDSL(rule.CelExpression, vars) {
				continue
			}
		}

		ruleType := strings.ToLower(rule.Type)
		ruleScope := strings.ToLower(rule.Scope)

		if ruleType == "drop" || ruleType == "filter" {
			matched := false
			switch ruleScope {
			case "response_header":
				for _, values := range resp.Header {
					for _, v := range values {
						if matchPattern(v, rule.Pattern) { matched = true; break }
					}
					if matched { break }
				}
			case "response_body": matched = matchPattern(string(body), rule.Pattern)
			case "all":
				if resp.Request != nil {
					matched = matchPattern(resp.Request.URL.String(), rule.Pattern) || matchPattern(string(body), rule.Pattern)
				} else {
					matched = matchPattern(string(body), rule.Pattern)
				}
			}
			if matched {
				log.Printf("[Rules] Drop triggered for response from %s", reqURL)
				return body, true
			}
		}

		if ruleType == "delay" && rule.DelayMs > 0 {
			matched := false
			switch ruleScope {
			case "url":
				if resp.Request != nil {
					matched = matchPattern(resp.Request.URL.String(), rule.Pattern)
				}
			case "response_body": matched = matchPattern(string(body), rule.Pattern)
			case "all":
				if resp.Request != nil {
					matched = matchPattern(resp.Request.URL.String(), rule.Pattern) || matchPattern(string(body), rule.Pattern)
				} else {
					matched = matchPattern(string(body), rule.Pattern)
				}
			}
			if matched {
				time.Sleep(time.Duration(rule.DelayMs) * time.Millisecond)
			}
		}

		if ruleType == "replace" || ruleType == "matchreplace" {
			switch ruleScope {
			case "response_header":
				for k, values := range resp.Header {
					for i, v := range values {
						if matchPattern(v, rule.Pattern) {
							resp.Header[k][i] = replacePattern(v, rule.Pattern, rule.Replacement)
							modified = true
						}
					}
				}
			case "response_body":
				bodyStr := string(body)
				if matchPattern(bodyStr, rule.Pattern) {
					body = []byte(replacePattern(bodyStr, rule.Pattern, rule.Replacement))
					modified = true
				}
			case "all":
				for k, values := range resp.Header {
					for i, v := range values {
						if matchPattern(v, rule.Pattern) { resp.Header[k][i] = replacePattern(v, rule.Pattern, rule.Replacement); modified = true }
					}
				}
				if matchPattern(string(body), rule.Pattern) {
					body = []byte(replacePattern(string(body), rule.Pattern, rule.Replacement))
					modified = true
				}
			}
		}
	}
	if modified {
		// Update Content-Length if body changed
		resp.ContentLength = int64(len(body))
		resp.Header.Set("Content-Length", fmt.Sprintf("%d", len(body)))
	}
	return body, false
}

func isInScope(r *http.Request) bool {
	rules := GetScopeRules()
	if len(rules) == 0 {
		return true
	}

	included := false
	hasIncludeRules := false

	for _, rule := range rules {
		if !rule.Enabled {
			continue
		}

		if rule.Protocol != "Any" && !strings.EqualFold(rule.Protocol, r.URL.Scheme) {
			continue
		}

		hostMatched := matchPattern(r.URL.Host, rule.Host)
		pathMatched := matchPattern(r.URL.Path, rule.Path)

		if hostMatched && pathMatched {
			if strings.EqualFold(rule.Type, "exclude") { return false }
			if strings.EqualFold(rule.Type, "include") { included = true }
		}

		if strings.EqualFold(rule.Type, "include") {
			hasIncludeRules = true
		}
	}

	if !hasIncludeRules { return true }
	return included
}

func shouldIntercept(r *http.Request, body []byte, category string) bool {
	rules := GetRules()
	followProxy := GetSetting("follow_proxy_rules", "true") == "true"
	for _, rule := range rules {
		if !rule.Enabled { continue }
		if rule.Category == category || (followProxy && rule.Category == "proxy") {
			matched := false
			switch strings.ToLower(rule.Scope) {
			case "url": matched = matchPattern(r.URL.String(), rule.Pattern)
			case "request_header":
				for _, values := range r.Header {
					for _, v := range values {
						if matchPattern(v, rule.Pattern) { matched = true; break }
					}
					if matched { break }
				}
			case "request_body": matched = matchPattern(string(body), rule.Pattern)
			case "all": matched = matchPattern(r.URL.String(), rule.Pattern) || matchPattern(string(body), rule.Pattern)
			}
			if matched { return true }
		}
	}
	return false
}

func shouldInterceptResponse(resp *http.Response, body []byte, category string) bool {
	rules := GetRules()
	followProxy := GetSetting("follow_proxy_rules", "true") == "true"
	for _, rule := range rules {
		if !rule.Enabled { continue }
		if rule.Category == category || (followProxy && rule.Category == "proxy") {
			matched := false
			switch strings.ToLower(rule.Scope) {
			case "response_header":
				for _, values := range resp.Header {
					for _, v := range values {
						if matchPattern(v, rule.Pattern) { matched = true; break }
					}
					if matched { break }
				}
			case "response_body": matched = matchPattern(string(body), rule.Pattern)
			case "all":
				if resp.Request != nil {
					matched = matchPattern(resp.Request.URL.String(), rule.Pattern) || matchPattern(string(body), rule.Pattern)
				} else {
					matched = matchPattern(string(body), rule.Pattern)
				}
			}
			if matched { return true }
		}
	}
	return false
}

func StopGoProxy() {
	if currentSrv != nil {
		log.Println("[Proxy] Stopping current proxy listener...")
		currentSrv.Close()
		currentSrv = nil
	}
}

func GetCACert() string {
	certBlock := &pem.Block{
		Type:  "CERTIFICATE",
		Bytes: goproxy.GoproxyCa.Certificate[0],
	}
	return string(pem.EncodeToMemory(certBlock))
}

func GetProxySettings() (string, int) {
	return currentAddr, currentPort
}

func RegenerateCA() error {
	log.Println("[Proxy] Regenerating Root CA...")
	
	priv, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		return err
	}

	serialNumberLimit := new(big.Int).Lsh(big.NewInt(1), 128)
	serialNumber, err := rand.Int(rand.Reader, serialNumberLimit)
	if err != nil {
		return err
	}

	template := x509.Certificate{
		SerialNumber: serialNumber,
		Subject: pkix.Name{
			Organization: []string{"Meowl Project"},
			CommonName:   "Meowl Root CA",
		},
		NotBefore:             time.Now().Add(-24 * time.Hour),
		NotAfter:              time.Now().AddDate(10, 0, 0),
		KeyUsage:              x509.KeyUsageCertSign | x509.KeyUsageDigitalSignature,
		ExtKeyUsage:           []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth, x509.ExtKeyUsageClientAuth},
		BasicConstraintsValid: true,
		IsCA:                  true,
	}

	derBytes, err := x509.CreateCertificate(rand.Reader, &template, &template, &priv.PublicKey, priv)
	if err != nil {
		return err
	}

	caCert = derBytes
	caKey, err = x509.MarshalPKCS8PrivateKey(priv)
	if err != nil {
		return err
	}

	goproxy.GoproxyCa.Certificate = [][]byte{derBytes}
	goproxy.GoproxyCa.PrivateKey = priv
	leaf, _ := x509.ParseCertificate(derBytes)
	goproxy.GoproxyCa.Leaf = leaf

	// Re-initialize OkConnect with new CA
	goproxy.OkConnect = &goproxy.ConnectAction{
		Action:    goproxy.ConnectAccept,
		TLSConfig: goproxy.TLSConfigFromCA(&goproxy.GoproxyCa),
	}

	log.Println("[Proxy] Root CA regenerated successfully.")
	return nil
}

func SetBreakpoints(request bool, response bool) {
	interceptMu.Lock()
	requestBreakpoint = request
	responseBreakpoint = response
	interceptMu.Unlock()
}

func getIPCached(host string) string {
	if val, ok := dnsCache.Load(host); ok {
		entry := val.(dnsEntry)
		if time.Now().Before(entry.expiry) { return entry.ips[0] }
	}
	ips, err := net.LookupIP(host)
	if err == nil && len(ips) > 0 {
		ip := ips[0].String()
		dnsCache.Store(host, dnsEntry{ips: []string{ip}, expiry: time.Now().Add(5 * time.Minute)})
		return ip
	}
	return host
}

func isFrontendResource(reqPath string) bool {
	ext := strings.ToLower(path.Ext(reqPath))
	staticExts := map[string]bool{
		".js": true, ".jsx": true, ".ts": true, ".tsx": true,
		".css": true, ".scss": true, ".less": true,
		".png": true, ".jpg": true, ".jpeg": true, ".gif": true,
		".svg": true, ".ico": true, ".webp": true,
		".woff": true, ".woff2": true, ".ttf": true, ".eot": true,
		".mp4": true, ".webm": true, ".map": true,
	}
	return staticExts[ext]
}

func StartGoProxy(hub *Hub, port int) {
	currentHub = hub
	currentPort = port
	addr := fmt.Sprintf(":%d", port)
	currentAddr = addr

	log.Printf("[Proxy] Starting Go-based Proxy Engine on %s", addr)
	LoadProxyPool()
	dynamicProxyFunc := GetProxyFunc()
	customResolver := GetCustomResolver()
	dialer := &net.Dialer{Timeout: 30 * time.Second, KeepAlive: 30 * time.Second}
	if customResolver != nil { dialer.Resolver = customResolver }

	tr := &http.Transport{
		Proxy: dynamicProxyFunc,
		DialContext: dialer.DialContext,
		ForceAttemptHTTP2: true,
		MaxIdleConns: 100,
		IdleConnTimeout: 90 * time.Second,
		TLSHandshakeTimeout: 10 * time.Second,
		ExpectContinueTimeout: 1 * time.Second,
	}
	http2.ConfigureTransport(tr)
	proxy.Tr = tr
	h3tr := &http3.Transport{TLSClientConfig: &tls.Config{InsecureSkipVerify: true}}

	go func() {
		for cmd := range hub.ControlCommands {
			switch cmd.Type {
			case traffic.ControlSignal_INTERCEPT_ON:
				interceptMu.Lock(); interceptEnabled = true; interceptMu.Unlock()
				hub.Broadcast <- WSMessage{Type: "intercept_state", Data: map[string]interface{}{"enabled": true}}
			case traffic.ControlSignal_INTERCEPT_OFF:
				interceptMu.Lock(); interceptEnabled = false; interceptMu.Unlock()
				hub.Broadcast <- WSMessage{Type: "intercept_state", Data: map[string]interface{}{"enabled": false}}
			case traffic.ControlSignal_RELEASE_REQUEST:
				pendingMu.Lock()
				if ch, ok := pendingRequests[cmd.TargetUid]; ok {
					ch <- InterceptSignal{Action: "forward", Payload: cmd.Payload}
					delete(pendingRequests, cmd.TargetUid)
					hub.Broadcast <- WSMessage{Type: "intercept_removed", Data: cmd.TargetUid}
				}
				pendingMu.Unlock()
			case traffic.ControlSignal_DROP_REQUEST:
				pendingMu.Lock()
				if ch, ok := pendingRequests[cmd.TargetUid]; ok {
					ch <- InterceptSignal{Action: "drop"}
					delete(pendingRequests, cmd.TargetUid)
					DeleteIntercept(cmd.TargetUid)
					hub.Broadcast <- WSMessage{Type: "intercept_removed", Data: cmd.TargetUid}
				}
				pendingMu.Unlock()
			case traffic.ControlSignal_RELEASE_AND_INTERCEPT_RESPONSE:
				pendingMu.Lock()
				if ch, ok := pendingRequests[cmd.TargetUid]; ok {
					interceptNextMu.Lock(); interceptResponseNext[cmd.TargetUid] = true; interceptNextMu.Unlock()
					ch <- InterceptSignal{Action: "forward", Payload: cmd.Payload}
					delete(pendingRequests, cmd.TargetUid)
					hub.Broadcast <- WSMessage{Type: "intercept_removed", Data: cmd.TargetUid}
				}
				pendingMu.Unlock()
			}
		}
	}()

	goproxy.OkConnect = &goproxy.ConnectAction{Action: goproxy.ConnectAccept, TLSConfig: goproxy.TLSConfigFromCA(&goproxy.GoproxyCa)}
	proxy.OnRequest().HandleConnect(goproxy.AlwaysMitm)

	proxy.OnRequest().DoFunc(func(r *http.Request, ctx *goproxy.ProxyCtx) (*http.Request, *http.Response) {
		if r.Method == "CONNECT" {
			return r, nil
		}
		
		if isFrontendResource(r.URL.Path) {
			return r, nil
		}

		uid := fmt.Sprintf("%p_%d", r, time.Now().UnixNano())
		forceH3 := GetSetting("force_http3_upstream", "false") == "true"
		if r.URL.Scheme == "https" && forceH3 {
			ctx.RoundTripper = goproxy.RoundTripperFunc(func(req *http.Request, ctx *goproxy.ProxyCtx) (*http.Response, error) { return h3tr.RoundTrip(req) })
		}

		var body []byte
		if r.Body != nil {
			body, _ = io.ReadAll(r.Body)
			r.Body = io.NopCloser(bytes.NewBuffer(body))
		}

		event := &traffic.TrafficEvent{
			Uid: uid, Method: r.Method, Host: r.Host, Path: r.URL.Path, Query: r.URL.RawQuery,
			Tls: r.URL.Scheme == "https" || r.TLS != nil, Protocol: r.Proto,
			Time: time.Now().Format("15:04:05"), StartTime: time.Now().Format(time.RFC3339),
			RequestRaw: dumpRequest(r, body), SourceIp: r.RemoteAddr, RequestSize: 0,
			Source: "Browser", Extension: path.Ext(r.URL.Path),
		}

		if host, port, err := net.SplitHostPort(r.RemoteAddr); err == nil {
			event.SourceIp = host
			fmt.Sscanf(port, "%d", &event.Lport)
		}
		if _, port, err := net.SplitHostPort(r.Host); err == nil {
			fmt.Sscanf(port, "%d", &event.Rport)
		} else {
			if r.URL.Scheme == "https" { event.Rport = 443 } else { event.Rport = 80 }
		}

		reqHeaderStr := ""
		for k, vv := range r.Header { for _, v := range vv { reqHeaderStr += fmt.Sprintf("%s: %s\n", k, v) } }
		reqLine := fmt.Sprintf("%s %s %s\n", r.Method, r.URL.RequestURI(), r.Proto)
		event.ReqHeadersSize = int64(len(reqHeaderStr) + len(reqLine))
		event.PayloadRequestSize = int64(len(body))
		event.RequestSize = event.ReqHeadersSize + event.PayloadRequestSize
		event.HeadersSize = event.ReqHeadersSize
		event.UrlLength = int64(len(r.URL.String()))
		event.Length = event.UrlLength
		if r.Header.Get("Cookie") != "" { event.HasCookie = true }

		idMu.Lock(); globalID++; idMu.Unlock()
		event.Id = uint32(globalID)
		ctx.UserData = event

		var drop bool
		body, drop = applyRequestRules(r, body, "proxy")
		if drop { return r, goproxy.NewResponse(r, goproxy.ContentTypeText, http.StatusForbidden, "Request dropped by Meowl Proxy Rule") }
		r.Body = io.NopCloser(bytes.NewBuffer(body))
		event.RequestRaw = dumpRequest(r, body)
		event.PayloadRequestSize = int64(len(body))
		event.RequestSize = event.ReqHeadersSize + event.PayloadRequestSize

		interceptMu.RLock()
		doIntercept := interceptEnabled && (requestBreakpoint || shouldIntercept(r, body, "intercept"))
		interceptMu.RUnlock()
		inScope := isInScope(r)

		if doIntercept {
			event.Source = "intercept"
			dbEvent := TrafficEventFromProto(event)
			InsertIntercept(&dbEvent)
			batch := &traffic.WSBatch{Events: []*traffic.TrafficEvent{event}}
			if data, err := proto.Marshal(batch); err == nil { hub.Broadcast <- WSMessage{Type: "new_traffic_bin", BinaryData: data} }

			signalChan := make(chan InterceptSignal)
			pendingMu.Lock(); pendingRequests[uid] = signalChan; pendingMu.Unlock()
			signal := <-signalChan
			if signal.Action == "drop" { return r, goproxy.NewResponse(r, goproxy.ContentTypeText, http.StatusForbidden, "Request dropped by Meowl Interceptor") }
			if signal.Payload != "" {
				applyEditedRequest(r, signal.Payload)
				event.RequestRaw = signal.Payload
				event.PayloadRequestSize = int64(len(signal.Payload) - int(event.ReqHeadersSize))
				event.RequestSize = event.ReqHeadersSize + event.PayloadRequestSize
				UpdateInterceptRequest(event.Uid, event.RequestRaw, event.PayloadRequestSize, event.RequestSize)
			}
		} else if inScope {
			batch := &traffic.WSBatch{Events: []*traffic.TrafficEvent{event}}
			if data, err := proto.Marshal(batch); err == nil { hub.Broadcast <- WSMessage{Type: "new_traffic_bin", BinaryData: data} }
		}

		return r, nil
	})

	proxy.OnResponse().DoFunc(func(resp *http.Response, ctx *goproxy.ProxyCtx) *http.Response {
		if resp == nil { return nil }
		event, ok := ctx.UserData.(*traffic.TrafficEvent)
		if !ok { return resp }

		event.StatusCode = int32(resp.StatusCode)
		fullMime := resp.Header.Get("Content-Type")
		if idx := strings.Index(fullMime, ";"); idx != -1 { event.MimeType = strings.TrimSpace(fullMime[:idx]) } else { event.MimeType = fullMime }

		if event.StartTime != "" {
			if st, err := time.Parse(time.RFC3339, event.StartTime); err == nil { event.Latency = int32(time.Since(st).Milliseconds()) }
		}
		event.EndTime = time.Now().Format(time.RFC3339)
		if resp.Header.Get("Set-Cookie") != "" { event.HasCookie = true; event.SetCookies = int32(len(resp.Header["Set-Cookie"])) }

		var body []byte
		if resp.Body != nil {
			body, _ = io.ReadAll(resp.Body)
			var drop bool
			body, drop = applyResponseRules(resp, body, "proxy")
			if drop { return goproxy.NewResponse(resp.Request, goproxy.ContentTypeText, http.StatusForbidden, "Response dropped by Meowl Proxy Rule") }
			resp.Body = io.NopCloser(bytes.NewBuffer(body))
		}

		resHeaderStr := ""
		for k, vv := range resp.Header { for _, v := range vv { resHeaderStr += fmt.Sprintf("%s: %s\n", k, v) } }
		resLine := fmt.Sprintf("%s %d %s\n", resp.Proto, resp.StatusCode, http.StatusText(resp.StatusCode))
		event.ResHeadersSize = int64(len(resHeaderStr) + len(resLine))
		event.HeadersSize = event.ReqHeadersSize + event.ResHeadersSize
		event.PayloadResponseSize = int64(len(body))
		event.Size = event.ResHeadersSize + event.PayloadResponseSize
		event.ResponseRaw = dumpResponse(resp, body)

		if resp.Request != nil {
			host := resp.Request.Host
			if h, _, err := net.SplitHostPort(host); err == nil { host = h }
			event.ServerIp = getIPCached(host)
		}
		if strings.Contains(strings.ToLower(event.MimeType), "html") { event.Title = extractTitle(body) }

		interceptNextMu.Lock(); perRequestIntercept := interceptResponseNext[event.Uid]; delete(interceptResponseNext, event.Uid); interceptNextMu.Unlock()
		interceptMu.RLock(); wasIntercepted := event.Source == "intercept"; doIntercept := interceptEnabled && (responseBreakpoint || perRequestIntercept || shouldInterceptResponse(resp, body, "intercept")); interceptMu.RUnlock()

		if doIntercept {
			if !wasIntercepted {
				event.Source = "intercept"
				dbEvent := TrafficEventFromProto(event); InsertIntercept(&dbEvent)
			}
			UpdateInterceptWithResponse(event.Uid, int(event.StatusCode), event.ResponseRaw, event.EndTime, int(event.Latency), event.TlsIssuer)
			batch := &traffic.WSBatch{Events: []*traffic.TrafficEvent{event}}
			if data, err := proto.Marshal(batch); err == nil { hub.Broadcast <- WSMessage{Type: "new_traffic_bin", BinaryData: data} }

			signalChan := make(chan InterceptSignal)
			pendingMu.Lock(); pendingRequests[event.Uid] = signalChan; pendingMu.Unlock()
			signal := <-signalChan
			if signal.Action == "drop" { return goproxy.NewResponse(ctx.Req, goproxy.ContentTypeText, http.StatusForbidden, "Response dropped by Meowl Interceptor") }
			if signal.Payload != "" {
				applyEditedResponse(resp, signal.Payload)
				body, _ = io.ReadAll(resp.Body); resp.Body = io.NopCloser(bytes.NewBuffer(body))
				event.ResponseRaw = signal.Payload
				event.StatusCode = int32(resp.StatusCode)
				event.PayloadResponseSize = int64(len(body))
				event.Size = event.ResHeadersSize + event.PayloadResponseSize
			}
		}

		if !isInScope(ctx.Req) { return resp }
		dbEvent := TrafficEventFromProto(event)
		if !MoveInterceptToHistory(event.Uid, int(event.StatusCode), event.ResponseRaw, event.RequestRaw, event.EndTime, int(event.Latency), event.TlsIssuer) { InsertRequest(&dbEvent) }
		
		PassivelyScanTraffic(event)
		
		batch := &traffic.WSBatch{Events: []*traffic.TrafficEvent{event}}
		if data, err := proto.Marshal(batch); err == nil { hub.Broadcast <- WSMessage{Type: "new_traffic_bin", BinaryData: data} }
		return resp
	})

	currentSrv = &http.Server{Addr: addr, Handler: proxy}
	go func() { if err := currentSrv.ListenAndServe(); err != nil && err != http.ErrServerClosed { log.Printf("[Proxy] Error: %v", err) } }()
}

func applyEditedRequest(r *http.Request, raw string) {
	parts := strings.SplitN(raw, "\n\n", 2); headerBlock := parts[0]; var newBody string; if len(parts) > 1 { newBody = parts[1] }
	lines := strings.Split(headerBlock, "\n"); if len(lines) == 0 { return }
	reqParts := strings.SplitN(strings.TrimSpace(lines[0]), " ", 3)
	if len(reqParts) >= 2 {
		r.Method = reqParts[0]; if p, err := url.Parse(reqParts[1]); err == nil { r.URL = p; if p.Host != "" { r.Host = p.Host } }
	}
	r.Header = make(http.Header)
	for _, line := range lines[1:] {
		if cIdx := strings.Index(line, ":"); cIdx > 0 {
			k, v := strings.TrimSpace(line[:cIdx]), strings.TrimSpace(line[cIdx+1:])
			r.Header.Add(k, v); if strings.EqualFold(k, "Host") { r.Host = v }
		}
	}
	bodyBytes := []byte(newBody); r.Body = io.NopCloser(bytes.NewBuffer(bodyBytes)); r.ContentLength = int64(len(bodyBytes))
}

func applyEditedResponse(resp *http.Response, raw string) {
	parts := strings.SplitN(raw, "\n\n", 2); headerBlock := parts[0]; var newBody string; if len(parts) > 1 { newBody = parts[1] }
	lines := strings.Split(headerBlock, "\n"); if len(lines) == 0 { return }
	stParts := strings.SplitN(strings.TrimSpace(lines[0]), " ", 3)
	if len(stParts) >= 2 { fmt.Sscanf(stParts[1], "%d", &resp.StatusCode) }
	resp.Header = make(http.Header)
	for _, line := range lines[1:] {
		if cIdx := strings.Index(line, ":"); cIdx > 0 { resp.Header.Add(strings.TrimSpace(line[:cIdx]), strings.TrimSpace(line[cIdx+1:])) }
	}
	bodyBytes := []byte(newBody); resp.Body = io.NopCloser(bytes.NewBuffer(bodyBytes)); resp.ContentLength = int64(len(bodyBytes))
}

func ResendRequest(rawReq string, targetHost string, useTLS bool) (string, error) {
	parts := strings.SplitN(rawReq, "\n\n", 2); headerBlock := parts[0]; bodyStr := ""; if len(parts) > 1 { bodyStr = parts[1] }
	lines := strings.Split(headerBlock, "\n"); if len(lines) == 0 { return "", fmt.Errorf("empty") }
	reqParts := strings.SplitN(strings.TrimSpace(lines[0]), " ", 3)
	method, path := "GET", "/"; if len(reqParts) >= 1 { method = reqParts[0] }; if len(reqParts) >= 2 { path = reqParts[1] }
	if targetHost == "" {
		for _, l := range lines[1:] {
			if strings.HasPrefix(strings.ToLower(l), "host:") { targetHost = strings.TrimSpace(l[5:]); break }
		}
	}
	scheme := "http"; if useTLS || strings.Contains(targetHost, ":443") { scheme = "https" }
	fullURL := path; if !strings.HasPrefix(path, "http") { fullURL = fmt.Sprintf("%s://%s%s", scheme, targetHost, path) }
	req, err := http.NewRequest(method, fullURL, strings.NewReader(bodyStr)); if err != nil { return "", err }
	for _, l := range lines[1:] {
		if cIdx := strings.Index(l, ":"); cIdx > 0 { req.Header.Add(strings.TrimSpace(l[:cIdx]), strings.TrimSpace(l[cIdx+1:])) }
	}
	client := &http.Client{Timeout: 30 * time.Second}
	startTime := time.Now(); resp, err := client.Do(req); if err != nil { return "", err }
	defer resp.Body.Close(); latency := int(time.Since(startTime).Milliseconds())
	respBody, _ := io.ReadAll(resp.Body); responseRaw := dumpResponse(resp, respBody)

	// Minimal TrafficEvent for history
	uid := fmt.Sprintf("rep-%d", time.Now().UnixNano())
	dbEvent := TrafficEvent{
		UID: uid, Method: method, Host: targetHost, Path: req.URL.Path, Query: req.URL.RawQuery,
		StatusCode: resp.StatusCode, MimeType: resp.Header.Get("Content-Type"), Size: int64(len(respBody)),
		Protocol: resp.Proto, TLS: useTLS, ServerIP: getIPCached(targetHost), SourceIP: "127.0.0.1",
		RequestRaw: rawReq, ResponseRaw: responseRaw, Latency: latency, Source: "repeater",
		Time: startTime.Format("15:04:05"), StartTime: startTime.Format(time.RFC3339), EndTime: time.Now().Format(time.RFC3339),
		RPort: 0, LPort: 0, // Mock for repeater
	}
	InsertRequest(&dbEvent)
	if currentHub != nil {
		protoEvent := &traffic.TrafficEvent{
			Uid: uid, Id: uint32(dbEvent.ID), Method: method, Host: targetHost, Path: req.URL.Path,
			StatusCode: int32(resp.StatusCode), MimeType: dbEvent.MimeType, Size: dbEvent.Size,
			Protocol: resp.Proto, Tls: useTLS, Latency: int32(latency), Source: "repeater",
		}
		batch := &traffic.WSBatch{Events: []*traffic.TrafficEvent{protoEvent}}
		if data, err := proto.Marshal(batch); err == nil { currentHub.Broadcast <- WSMessage{Type: "new_traffic_bin", BinaryData: data} }
	}
	return responseRaw, nil
}

func dumpRequest(r *http.Request, body []byte) string {
	res := fmt.Sprintf("%s %s %s\n", r.Method, r.URL.RequestURI(), r.Proto)
	for k, vv := range r.Header { for _, v := range vv { res += fmt.Sprintf("%s: %s\n", k, v) } }
	res += "\n" + string(body)
	return res
}

func dumpResponse(resp *http.Response, body []byte) string {
	res := fmt.Sprintf("%s %d %s\n", resp.Proto, resp.StatusCode, http.StatusText(resp.StatusCode))
	for k, vv := range resp.Header { for _, v := range vv { res += fmt.Sprintf("%s: %s\n", k, v) } }
	res += "\n" + string(body)
	return res
}

func extractTitle(body []byte) string {
	re := regexp.MustCompile("(?i)<title>(.*?)</title>")
	matches := re.FindSubmatch(body)
	if len(matches) > 1 { return string(matches[1]) }
	return ""
}

func TrafficEventFromProto(e *traffic.TrafficEvent) TrafficEvent {
	return TrafficEvent{
		UID: e.Uid, Method: e.Method, Host: e.Host, Path: e.Path, Query: e.Query,
		StatusCode: int(e.StatusCode), MimeType: e.MimeType, Size: e.Size,
		Protocol: e.Protocol, TLS: e.Tls, ServerIP: e.ServerIp, SourceIP: e.SourceIp,
		RequestRaw: e.RequestRaw, ResponseRaw: e.ResponseRaw, Extension: e.Extension,
		Latency: int(e.Latency), Source: e.Source, Time: e.Time, StartTime: e.StartTime, EndTime: e.EndTime,
		RPort: int(e.Rport), LPort: int(e.Lport), HasCookie: e.HasCookie, Title: e.Title,
	}
}
