// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckProxyPool(arg1) {
  return window['go']['backend']['App']['CheckProxyPool'](arg1);
}

export function GetCACert() {
  return window['go']['backend']['App']['GetCACert']();
}

export function GetFuzzResponse(arg1) {
  return window['go']['backend']['App']['GetFuzzResponse'](arg1);
}

export function GetNetworkConfig() {
  return window['go']['backend']['App']['GetNetworkConfig']();
}

export function GetProxySettings() {
  return window['go']['backend']['App']['GetProxySettings']();
}

export function GetRules() {
  return window['go']['backend']['App']['GetRules']();
}

export function GetScopeRules() {
  return window['go']['backend']['App']['GetScopeRules']();
}

export function GetSetting(arg1, arg2) {
  return window['go']['backend']['App']['GetSetting'](arg1, arg2);
}

export function PauseFuzzer() {
  return window['go']['backend']['App']['PauseFuzzer']();
}

export function RegenerateCA() {
  return window['go']['backend']['App']['RegenerateCA']();
}

export function ResendRequest(arg1, arg2, arg3) {
  return window['go']['backend']['App']['ResendRequest'](arg1, arg2, arg3);
}

export function RestartProxy() {
  return window['go']['backend']['App']['RestartProxy']();
}

export function ResumeFuzzer() {
  return window['go']['backend']['App']['ResumeFuzzer']();
}

export function SaveNetworkConfig(arg1) {
  return window['go']['backend']['App']['SaveNetworkConfig'](arg1);
}

export function SaveRules(arg1) {
  return window['go']['backend']['App']['SaveRules'](arg1);
}

export function SaveScopeRules(arg1) {
  return window['go']['backend']['App']['SaveScopeRules'](arg1);
}

export function SelectImage() {
  return window['go']['backend']['App']['SelectImage']();
}

export function SetProxySettings(arg1) {
  return window['go']['backend']['App']['SetProxySettings'](arg1);
}

export function SetSetting(arg1, arg2) {
  return window['go']['backend']['App']['SetSetting'](arg1, arg2);
}

export function StartFuzzer(arg1) {
  return window['go']['backend']['App']['StartFuzzer'](arg1);
}

export function StartSpider(arg1) {
  return window['go']['backend']['App']['StartSpider'](arg1);
}

export function StopFuzzer() {
  return window['go']['backend']['App']['StopFuzzer']();
}

export function StopSpider() {
  return window['go']['backend']['App']['StopSpider']();
}
