// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function CheckProxyPool(arg1:string):Promise<Array<backend.CheckResult>>;

export function GetCACert():Promise<string>;

export function GetFuzzResponse(arg1:string):Promise<Record<string, any>>;

export function GetNetworkConfig():Promise<string>;

export function GetProxySettings():Promise<Record<string, any>>;

export function GetRules():Promise<Array<backend.Rule>>;

export function GetScopeRules():Promise<Array<backend.ScopeRule>>;

export function GetSetting(arg1:string,arg2:string):Promise<string>;

export function PauseFuzzer():Promise<void>;

export function RegenerateCA():Promise<string>;

export function ResendRequest(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function RestartProxy():Promise<void>;

export function ResumeFuzzer():Promise<void>;

export function SaveCustomScripts(arg1:Array<backend.CustomScript>):Promise<void>;

export function SaveNetworkConfig(arg1:string):Promise<void>;

export function SaveRules(arg1:Array<backend.Rule>):Promise<string>;

export function SaveScopeRules(arg1:Array<backend.ScopeRule>):Promise<string>;

export function SelectImage():Promise<string>;

export function SetProxySettings(arg1:number):Promise<boolean>;

export function SetSetting(arg1:string,arg2:string):Promise<string>;

export function StartFuzzer(arg1:backend.FuzzOptions):Promise<void>;

export function StartSpider(arg1:backend.SpiderConfig):Promise<void>;

export function StopFuzzer():Promise<void>;

export function StopSpider():Promise<void>;
