// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: backend/traffic/traffic.proto

package traffic

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ControlSignal_Type int32

const (
	ControlSignal_INTERCEPT_ON                   ControlSignal_Type = 0
	ControlSignal_INTERCEPT_OFF                  ControlSignal_Type = 1
	ControlSignal_RELEASE_REQUEST                ControlSignal_Type = 2
	ControlSignal_DROP_REQUEST                   ControlSignal_Type = 3
	ControlSignal_RELEASE_AND_INTERCEPT_RESPONSE ControlSignal_Type = 4
)

// Enum value maps for ControlSignal_Type.
var (
	ControlSignal_Type_name = map[int32]string{
		0: "INTERCEPT_ON",
		1: "INTERCEPT_OFF",
		2: "RELEASE_REQUEST",
		3: "DROP_REQUEST",
		4: "RELEASE_AND_INTERCEPT_RESPONSE",
	}
	ControlSignal_Type_value = map[string]int32{
		"INTERCEPT_ON":                   0,
		"INTERCEPT_OFF":                  1,
		"RELEASE_REQUEST":                2,
		"DROP_REQUEST":                   3,
		"RELEASE_AND_INTERCEPT_RESPONSE": 4,
	}
)

func (x ControlSignal_Type) Enum() *ControlSignal_Type {
	p := new(ControlSignal_Type)
	*p = x
	return p
}

func (x ControlSignal_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlSignal_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_backend_traffic_traffic_proto_enumTypes[0].Descriptor()
}

func (ControlSignal_Type) Type() protoreflect.EnumType {
	return &file_backend_traffic_traffic_proto_enumTypes[0]
}

func (x ControlSignal_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlSignal_Type.Descriptor instead.
func (ControlSignal_Type) EnumDescriptor() ([]byte, []int) {
	return file_backend_traffic_traffic_proto_rawDescGZIP(), []int{1, 0}
}

type TrafficEvent struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Uid                 string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Id                  uint32                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Method              string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Host                string                 `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	Path                string                 `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	Query               string                 `protobuf:"bytes,6,opt,name=query,proto3" json:"query,omitempty"`
	StatusCode          int32                  `protobuf:"varint,7,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Size                int64                  `protobuf:"varint,8,opt,name=size,proto3" json:"size,omitempty"`
	RequestSize         int64                  `protobuf:"varint,9,opt,name=request_size,json=requestSize,proto3" json:"request_size,omitempty"`
	Latency             int32                  `protobuf:"varint,10,opt,name=latency,proto3" json:"latency,omitempty"`
	MimeType            string                 `protobuf:"bytes,11,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Tls                 bool                   `protobuf:"varint,12,opt,name=tls,proto3" json:"tls,omitempty"`
	Protocol            string                 `protobuf:"bytes,13,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Lport               int32                  `protobuf:"varint,14,opt,name=lport,proto3" json:"lport,omitempty"`
	Rport               int32                  `protobuf:"varint,15,opt,name=rport,proto3" json:"rport,omitempty"`
	SourceIp            string                 `protobuf:"bytes,16,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	ServerIp            string                 `protobuf:"bytes,17,opt,name=server_ip,json=serverIp,proto3" json:"server_ip,omitempty"`
	HasCookie           bool                   `protobuf:"varint,18,opt,name=has_cookie,json=hasCookie,proto3" json:"has_cookie,omitempty"`
	Extension           string                 `protobuf:"bytes,19,opt,name=extension,proto3" json:"extension,omitempty"`
	Source              string                 `protobuf:"bytes,20,opt,name=source,proto3" json:"source,omitempty"`
	Title               string                 `protobuf:"bytes,21,opt,name=title,proto3" json:"title,omitempty"`
	TlsIssuer           string                 `protobuf:"bytes,22,opt,name=tls_issuer,json=tlsIssuer,proto3" json:"tls_issuer,omitempty"`
	SetCookies          int32                  `protobuf:"varint,23,opt,name=set_cookies,json=setCookies,proto3" json:"set_cookies,omitempty"`
	RequestRaw          string                 `protobuf:"bytes,24,opt,name=request_raw,json=requestRaw,proto3" json:"request_raw,omitempty"`
	ResponseRaw         string                 `protobuf:"bytes,25,opt,name=response_raw,json=responseRaw,proto3" json:"response_raw,omitempty"`
	Time                string                 `protobuf:"bytes,26,opt,name=time,proto3" json:"time,omitempty"`
	Length              int64                  `protobuf:"varint,27,opt,name=length,proto3" json:"length,omitempty"`
	PayloadRequestSize  int64                  `protobuf:"varint,28,opt,name=payload_request_size,json=payloadRequestSize,proto3" json:"payload_request_size,omitempty"`
	PayloadResponseSize int64                  `protobuf:"varint,29,opt,name=payload_response_size,json=payloadResponseSize,proto3" json:"payload_response_size,omitempty"`
	HeadersSize         int64                  `protobuf:"varint,30,opt,name=headers_size,json=headersSize,proto3" json:"headers_size,omitempty"`
	StartTime           string                 `protobuf:"bytes,31,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime             string                 `protobuf:"bytes,32,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	RequestBody         []byte                 `protobuf:"bytes,33,opt,name=request_body,json=requestBody,proto3" json:"request_body,omitempty"`
	ResponseBody        []byte                 `protobuf:"bytes,34,opt,name=response_body,json=responseBody,proto3" json:"response_body,omitempty"`
	ReqHeadersSize      int64                  `protobuf:"varint,35,opt,name=req_headers_size,json=reqHeadersSize,proto3" json:"req_headers_size,omitempty"`
	ResHeadersSize      int64                  `protobuf:"varint,36,opt,name=res_headers_size,json=resHeadersSize,proto3" json:"res_headers_size,omitempty"`
	UrlLength           int64                  `protobuf:"varint,37,opt,name=url_length,json=urlLength,proto3" json:"url_length,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TrafficEvent) Reset() {
	*x = TrafficEvent{}
	mi := &file_backend_traffic_traffic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficEvent) ProtoMessage() {}

func (x *TrafficEvent) ProtoReflect() protoreflect.Message {
	mi := &file_backend_traffic_traffic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficEvent.ProtoReflect.Descriptor instead.
func (*TrafficEvent) Descriptor() ([]byte, []int) {
	return file_backend_traffic_traffic_proto_rawDescGZIP(), []int{0}
}

func (x *TrafficEvent) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *TrafficEvent) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TrafficEvent) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *TrafficEvent) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *TrafficEvent) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *TrafficEvent) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *TrafficEvent) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *TrafficEvent) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *TrafficEvent) GetRequestSize() int64 {
	if x != nil {
		return x.RequestSize
	}
	return 0
}

func (x *TrafficEvent) GetLatency() int32 {
	if x != nil {
		return x.Latency
	}
	return 0
}

func (x *TrafficEvent) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *TrafficEvent) GetTls() bool {
	if x != nil {
		return x.Tls
	}
	return false
}

func (x *TrafficEvent) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *TrafficEvent) GetLport() int32 {
	if x != nil {
		return x.Lport
	}
	return 0
}

func (x *TrafficEvent) GetRport() int32 {
	if x != nil {
		return x.Rport
	}
	return 0
}

func (x *TrafficEvent) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *TrafficEvent) GetServerIp() string {
	if x != nil {
		return x.ServerIp
	}
	return ""
}

func (x *TrafficEvent) GetHasCookie() bool {
	if x != nil {
		return x.HasCookie
	}
	return false
}

func (x *TrafficEvent) GetExtension() string {
	if x != nil {
		return x.Extension
	}
	return ""
}

func (x *TrafficEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *TrafficEvent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TrafficEvent) GetTlsIssuer() string {
	if x != nil {
		return x.TlsIssuer
	}
	return ""
}

func (x *TrafficEvent) GetSetCookies() int32 {
	if x != nil {
		return x.SetCookies
	}
	return 0
}

func (x *TrafficEvent) GetRequestRaw() string {
	if x != nil {
		return x.RequestRaw
	}
	return ""
}

func (x *TrafficEvent) GetResponseRaw() string {
	if x != nil {
		return x.ResponseRaw
	}
	return ""
}

func (x *TrafficEvent) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *TrafficEvent) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *TrafficEvent) GetPayloadRequestSize() int64 {
	if x != nil {
		return x.PayloadRequestSize
	}
	return 0
}

func (x *TrafficEvent) GetPayloadResponseSize() int64 {
	if x != nil {
		return x.PayloadResponseSize
	}
	return 0
}

func (x *TrafficEvent) GetHeadersSize() int64 {
	if x != nil {
		return x.HeadersSize
	}
	return 0
}

func (x *TrafficEvent) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *TrafficEvent) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *TrafficEvent) GetRequestBody() []byte {
	if x != nil {
		return x.RequestBody
	}
	return nil
}

func (x *TrafficEvent) GetResponseBody() []byte {
	if x != nil {
		return x.ResponseBody
	}
	return nil
}

func (x *TrafficEvent) GetReqHeadersSize() int64 {
	if x != nil {
		return x.ReqHeadersSize
	}
	return 0
}

func (x *TrafficEvent) GetResHeadersSize() int64 {
	if x != nil {
		return x.ResHeadersSize
	}
	return 0
}

func (x *TrafficEvent) GetUrlLength() int64 {
	if x != nil {
		return x.UrlLength
	}
	return 0
}

type ControlSignal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ControlSignal_Type     `protobuf:"varint,1,opt,name=type,proto3,enum=traffic.ControlSignal_Type" json:"type,omitempty"`
	TargetUid     string                 `protobuf:"bytes,2,opt,name=target_uid,json=targetUid,proto3" json:"target_uid,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlSignal) Reset() {
	*x = ControlSignal{}
	mi := &file_backend_traffic_traffic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlSignal) ProtoMessage() {}

func (x *ControlSignal) ProtoReflect() protoreflect.Message {
	mi := &file_backend_traffic_traffic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlSignal.ProtoReflect.Descriptor instead.
func (*ControlSignal) Descriptor() ([]byte, []int) {
	return file_backend_traffic_traffic_proto_rawDescGZIP(), []int{1}
}

func (x *ControlSignal) GetType() ControlSignal_Type {
	if x != nil {
		return x.Type
	}
	return ControlSignal_INTERCEPT_ON
}

func (x *ControlSignal) GetTargetUid() string {
	if x != nil {
		return x.TargetUid
	}
	return ""
}

func (x *ControlSignal) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type WSBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*TrafficEvent        `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WSBatch) Reset() {
	*x = WSBatch{}
	mi := &file_backend_traffic_traffic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WSBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WSBatch) ProtoMessage() {}

func (x *WSBatch) ProtoReflect() protoreflect.Message {
	mi := &file_backend_traffic_traffic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WSBatch.ProtoReflect.Descriptor instead.
func (*WSBatch) Descriptor() ([]byte, []int) {
	return file_backend_traffic_traffic_proto_rawDescGZIP(), []int{2}
}

func (x *WSBatch) GetEvents() []*TrafficEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_backend_traffic_traffic_proto protoreflect.FileDescriptor

const file_backend_traffic_traffic_proto_rawDesc = "" +
	"\n" +
	"\x1dbackend/traffic/traffic.proto\x12\atraffic\"\xc2\b\n" +
	"\fTrafficEvent\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\rR\x02id\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x12\n" +
	"\x04host\x18\x04 \x01(\tR\x04host\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\x12\x14\n" +
	"\x05query\x18\x06 \x01(\tR\x05query\x12\x1f\n" +
	"\vstatus_code\x18\a \x01(\x05R\n" +
	"statusCode\x12\x12\n" +
	"\x04size\x18\b \x01(\x03R\x04size\x12!\n" +
	"\frequest_size\x18\t \x01(\x03R\vrequestSize\x12\x18\n" +
	"\alatency\x18\n" +
	" \x01(\x05R\alatency\x12\x1b\n" +
	"\tmime_type\x18\v \x01(\tR\bmimeType\x12\x10\n" +
	"\x03tls\x18\f \x01(\bR\x03tls\x12\x1a\n" +
	"\bprotocol\x18\r \x01(\tR\bprotocol\x12\x14\n" +
	"\x05lport\x18\x0e \x01(\x05R\x05lport\x12\x14\n" +
	"\x05rport\x18\x0f \x01(\x05R\x05rport\x12\x1b\n" +
	"\tsource_ip\x18\x10 \x01(\tR\bsourceIp\x12\x1b\n" +
	"\tserver_ip\x18\x11 \x01(\tR\bserverIp\x12\x1d\n" +
	"\n" +
	"has_cookie\x18\x12 \x01(\bR\thasCookie\x12\x1c\n" +
	"\textension\x18\x13 \x01(\tR\textension\x12\x16\n" +
	"\x06source\x18\x14 \x01(\tR\x06source\x12\x14\n" +
	"\x05title\x18\x15 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"tls_issuer\x18\x16 \x01(\tR\ttlsIssuer\x12\x1f\n" +
	"\vset_cookies\x18\x17 \x01(\x05R\n" +
	"setCookies\x12\x1f\n" +
	"\vrequest_raw\x18\x18 \x01(\tR\n" +
	"requestRaw\x12!\n" +
	"\fresponse_raw\x18\x19 \x01(\tR\vresponseRaw\x12\x12\n" +
	"\x04time\x18\x1a \x01(\tR\x04time\x12\x16\n" +
	"\x06length\x18\x1b \x01(\x03R\x06length\x120\n" +
	"\x14payload_request_size\x18\x1c \x01(\x03R\x12payloadRequestSize\x122\n" +
	"\x15payload_response_size\x18\x1d \x01(\x03R\x13payloadResponseSize\x12!\n" +
	"\fheaders_size\x18\x1e \x01(\x03R\vheadersSize\x12\x1d\n" +
	"\n" +
	"start_time\x18\x1f \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18  \x01(\tR\aendTime\x12!\n" +
	"\frequest_body\x18! \x01(\fR\vrequestBody\x12#\n" +
	"\rresponse_body\x18\" \x01(\fR\fresponseBody\x12(\n" +
	"\x10req_headers_size\x18# \x01(\x03R\x0ereqHeadersSize\x12(\n" +
	"\x10res_headers_size\x18$ \x01(\x03R\x0eresHeadersSize\x12\x1d\n" +
	"\n" +
	"url_length\x18% \x01(\x03R\turlLength\"\xf1\x01\n" +
	"\rControlSignal\x12/\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1b.traffic.ControlSignal.TypeR\x04type\x12\x1d\n" +
	"\n" +
	"target_uid\x18\x02 \x01(\tR\ttargetUid\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\"v\n" +
	"\x04Type\x12\x10\n" +
	"\fINTERCEPT_ON\x10\x00\x12\x11\n" +
	"\rINTERCEPT_OFF\x10\x01\x12\x13\n" +
	"\x0fRELEASE_REQUEST\x10\x02\x12\x10\n" +
	"\fDROP_REQUEST\x10\x03\x12\"\n" +
	"\x1eRELEASE_AND_INTERCEPT_RESPONSE\x10\x04\"8\n" +
	"\aWSBatch\x12-\n" +
	"\x06events\x18\x01 \x03(\v2\x15.traffic.TrafficEventR\x06eventsB\x17Z\x15meowl/backend/trafficb\x06proto3"

var (
	file_backend_traffic_traffic_proto_rawDescOnce sync.Once
	file_backend_traffic_traffic_proto_rawDescData []byte
)

func file_backend_traffic_traffic_proto_rawDescGZIP() []byte {
	file_backend_traffic_traffic_proto_rawDescOnce.Do(func() {
		file_backend_traffic_traffic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backend_traffic_traffic_proto_rawDesc), len(file_backend_traffic_traffic_proto_rawDesc)))
	})
	return file_backend_traffic_traffic_proto_rawDescData
}

var file_backend_traffic_traffic_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_backend_traffic_traffic_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_backend_traffic_traffic_proto_goTypes = []any{
	(ControlSignal_Type)(0), // 0: traffic.ControlSignal.Type
	(*TrafficEvent)(nil),    // 1: traffic.TrafficEvent
	(*ControlSignal)(nil),   // 2: traffic.ControlSignal
	(*WSBatch)(nil),         // 3: traffic.WSBatch
}
var file_backend_traffic_traffic_proto_depIdxs = []int32{
	0, // 0: traffic.ControlSignal.type:type_name -> traffic.ControlSignal.Type
	1, // 1: traffic.WSBatch.events:type_name -> traffic.TrafficEvent
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_backend_traffic_traffic_proto_init() }
func file_backend_traffic_traffic_proto_init() {
	if File_backend_traffic_traffic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backend_traffic_traffic_proto_rawDesc), len(file_backend_traffic_traffic_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_backend_traffic_traffic_proto_goTypes,
		DependencyIndexes: file_backend_traffic_traffic_proto_depIdxs,
		EnumInfos:         file_backend_traffic_traffic_proto_enumTypes,
		MessageInfos:      file_backend_traffic_traffic_proto_msgTypes,
	}.Build()
	File_backend_traffic_traffic_proto = out.File
	file_backend_traffic_traffic_proto_goTypes = nil
	file_backend_traffic_traffic_proto_depIdxs = nil
}
